// Generated by LiveScript 1.4.0
(function(){
  var emitter, users, goods;
  emitter = require('./emitter').direct;
  users = require('./data').users;
  goods = require('./data').goods;
  /*async = require 'async'*/
  /* Registering users */
  emitter.post('/api/authenticate/register', '', users[0], function(err, result){
    emitter.post('/api/authenticate/register', '', users[1], function(err, result){
      emitter.post('/api/authenticate/register', '', users[2], function(err, result){});
    });
  });
  /* Login and get tokens */
  emitter.get('/api/authenticate/login', users[0], '', function(err, result){
    users[0].token = result.token;
    emitter.get('/api/authenticate/login', users[1], '', function(err, result){
      users[1].token = result.token;
      emitter.get('/api/authenticate/login', users[1], '', function(err, result){
        users[2].token = result.token;
      });
    });
  });
  /* Posting goods */
  emitter.post('/api/goods/post', users[0], goods[0], function(err, result){
    emitter.post('/api/goods/post', users[1], goods[1], function(err, result){
      emitter.post('/api/goods/post', users[2], goods[2], function(err, result){
        emitter.post('/api/goods/post', users[0], goods[3], function(err, result){
          emitter.post('/api/goods/post', users[1], goods[4], function(err, result){
            emitter.post('/api/goods/post', users[2], goods[5], function(err, result){});
          });
        });
      });
    });
  });
}).call(this);
