// Generated by LiveScript 1.4.0
(function(){
  var emitter, users, goods, log, check;
  emitter = require('./emitter').direct;
  users = require('./data').users;
  goods = require('./data').goods;
  /*async = require 'async'*/
  log = function(o){
    console.log(JSON.stringify(o));
  };
  check = function(o){
    console.log(o !== null ? '└─[Success]' : '└─[Fail]');
  };
  /* Registering users */
  emitter.post('/api/authenticate/register', '', users[0], '', function(err, result){
    check(result);
    emitter.post('/api/authenticate/register', '', users[1], '', function(err, result){
      check(result);
      emitter.post('/api/authenticate/register', '', users[2], '', function(err, result){
        check(result);
        /* Login and get tokens */
        emitter.get('/api/authenticate/login', users[0], '', '', function(err, result){
          check(result);
          users[0].token = result.token;
          emitter.get('/api/authenticate/login', users[1], '', '', function(err, result){
            check(result);
            users[1].token = result.token;
            emitter.get('/api/authenticate/login', users[1], '', '', function(err, result){
              check(result);
              users[2].token = result.token;
              /* Posting goods */
              emitter.post('/api/goods/post', users[0], goods[0], '', function(err, result){
                check(result);
                goods[0] = result;
                emitter.post('/api/goods/post', users[1], goods[1], '', function(err, result){
                  check(result);
                  goods[1] = result;
                  emitter.post('/api/goods/post', users[2], goods[2], '', function(err, result){
                    check(result);
                    goods[2] = result;
                    emitter.post('/api/goods/post', users[0], goods[3], '', function(err, result){
                      check(result);
                      goods[3] = result;
                      emitter.post('/api/goods/post', users[1], goods[4], '', function(err, result){
                        check(result);
                        goods[4] = result;
                        emitter.post('/api/goods/post', users[2], goods[5], '', function(err, result){
                          check(result);
                          goods[5] = result;
                          /* Getting goods */
                          emitter.get('/api/goods', {
                            gid: 1
                          }, '', users[1], function(err, result){
                            check(result);
                            emitter.get('/api/goods', {
                              gid: 2
                            }, '', users[2], function(err, result){
                              check(result);
                              emitter.get('/api/goods', {
                                gid: 3
                              }, '', users[0], function(err, result){
                                check(result);
                                emitter.get('/api/goods', {
                                  gid: 4
                                }, '', users[1], function(err, result){
                                  check(result);
                                  emitter.get('/api/goods', {
                                    gid: 5
                                  }, '', users[2], function(err, result){
                                    check(result);
                                    emitter.get('/api/goods', {
                                      gid: 6
                                    }, '', users[0], function(err, result){
                                      check(result);
                                      /* Getting goods of owner */
                                      emitter.get('/api/goods/of', {
                                        owner_uid: 1
                                      }, '', users[0], function(err, result){
                                        log(result);
                                        emitter.get('/api/goods/of', {
                                          owner_uid: 2
                                        }, '', users[1], function(err, result){
                                          log(result);
                                          emitter.get('/api/goods/of', {
                                            owner_uid: 3
                                          }, '', users[2], function(err, result){
                                            log(result);
                                            emitter.get('/api/goods/of', {
                                              owner_uid: 4
                                            }, '', users[3], function(err, result){
                                              log(result);
                                              /* Editting some goods */
                                              emitter.put('/api/goods/edit', '', function(){
                                                goods[0].name = 'lalalalala';
                                                return goods;
                                              }(), users[0], function(err, result){
                                                log(result);
                                              });
                                            });
                                          });
                                        });
                                      });
                                    });
                                  });
                                });
                              });
                            });
                          });
                        });
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
    });
  });
}).call(this);
